# Generated by Django 3.1.7 on 2021-03-15 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myprojectapp', '0005_auto_20210308_1308'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0, verbose_name='quantity')),
                ('add_datetime', models.DateTimeField(auto_now_add=True, verbose_name='time')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myprojectapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
